### PR TITLE
added Playlist, Song, QueuedSong

### PR DESCRIPTION
**Pull request by dhsiehcode**

### CODE REVIEW

**Review by ImTheSquid — CHANGES_REQUESTED** [review]
`Playlist::id` should be `Option<ObjectId>`, not `ObjectId`

**Comment by dhsiehcode** [comment]
I hope my fix is correct

**Review by ImTheSquid — DISMISSED** [review]
Make sure everything is pub

**Comment by dhsiehcode** [comment]
made things pub

**Review by thomas-lane — DISMISSED** [review]
Nice

**Review by thomas-lane — APPROVED** [review]

**Pull request merged**
